[browser] 
gatherUsageStats = false
serverAddress = "127.0.0.1"

[global]
showWarningOnDirectExecution = false

[server] 
headless = false
enableCORS = false 
enableXsrfProtection = false
address = "127.0.0.1"
port = 8501 

[client]
showErrorDetails = false
toolbarMode = "minimal"

# Prevent Altair from creating data files
[runner]
magicEnabled = false

# Chart configuration to minimize data file creation
[theme]
primaryColor = "#1f77b4"
